ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

#include $(MKFILES_ROOT)/qmacros.mk

#-include $(PROJECT_ROOT)/roots.mk


PUBLIC_HDR_PATH=$(QNX_TARGET)/usr/include/io-pkt

NAME = $(PROJECT)
USEFILE=

LIBS += socket
LIBS += pcap

EXTRA_INCVPATH += $(PUBLIC_HDR_PATH) $(PUBLIC_HDR_PATH)/sys-nto $(QNX_TARGET)/usr/include 
EXTRA_INCVPATH += $(PROJECT_ROOT)/src/include

EXTRA_SRCVPATH += $(PROJECT_ROOT)/src

include $(MKFILES_ROOT)/qmacros.mk
ifndef QNX_INTERNAL
QNX_INTERNAL=$(PROJECT_ROOT)/.qnx_internal.mk
endif
include $(QNX_INTERNAL)

define PINFO
PINFO DESCRIPTION=QNX SDIO performance test for wave driver
endef
  
include $(MKFILES_ROOT)/qtargets.mk
#####AUTO-GENERATED by packaging script... do not checkin#####
#   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
#   USE_INSTALL_ROOT=1
##############################################################
